CREATE TABLE IF NOT EXISTS admins (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(120) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  name_en VARCHAR(120) NOT NULL,
  province VARCHAR(120) NOT NULL,
  adcode VARCHAR(16) NOT NULL,
  coord_x DECIMAL(10,6) NOT NULL,
  coord_y DECIMAL(10,6) NOT NULL,
  description TEXT NULL,
  gear VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS photos (
  id CHAR(36) NOT NULL PRIMARY KEY,
  city_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  shot_at DATE NULL,
  camera VARCHAR(255) NULL,
  location_name VARCHAR(255) NULL,
  district_code VARCHAR(32) NULL,
  district_name VARCHAR(120) NULL,
  street_name VARCHAR(255) NULL,
  longitude DECIMAL(10,6) NULL,
  latitude DECIMAL(10,6) NULL,
  description TEXT NULL,
  image_url TEXT NOT NULL,
  is_cover TINYINT(1) NOT NULL DEFAULT 0,
  is_published TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_photos_city FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS photo_tags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  photo_id CHAR(36) NOT NULL,
  tag VARCHAR(120) NOT NULL,
  CONSTRAINT fk_photo_tags_photo FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE
);
